CREATE TABLE countries(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(40) NOT NULL UNIQUE,
	continent VARCHAR(40) NOT NULL,
	currency VARCHAR(5)
);

CREATE TABLE categories(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE actors(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	birthdate DATE NOT NULL,
	height INT,
	awards INT NOT NULL DEFAULT 0 CHECK(awards >= 0),
	country_id INT NOT NULL REFERENCES countries ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE productions_info(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	rating DECIMAL(4, 2) NOT NULL,
	duration INT NOT NULL CHECK(duration > 0),
	budget DECIMAL(10, 2),
	release_date DATE NOT NULL,
	has_subtitles BOOLEAN NOT NULL DEFAULT FALSE,
	synopsis TEXT
);

CREATE TABLE productions(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	title VARCHAR(70) NOT NULL UNIQUE,
	country_id INT NOT NULL REFERENCES countries ON UPDATE CASCADE ON DELETE CASCADE,
	production_info_id INT NOT NULL REFERENCES productions_info ON UPDATE CASCADE ON DELETE CASCADE UNIQUE
);

CREATE TABLE productions_actors(
	production_id INT NOT NULL REFERENCES productions ON UPDATE CASCADE ON DELETE CASCADE, 
	actor_id INT NOT NULL REFERENCES actors ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY (production_id, actor_id)
);

CREATE TABLE categories_productions(
	category_id INT NOT NULL REFERENCES categories ON UPDATE CASCADE ON DELETE CASCADE,
	production_id INT NOT NULL REFERENCES productions ON UPDATE CASCADE ON DELETE CASCADE,

	PRIMARY KEY (category_id, production_id)
);
